# The URL the site will be built for
base_url = "https://tesselode.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

taxonomies = [{ name = "tags", render = false }]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
	{ theme = "ayu-dark", filename = "syntax-theme-dark.css" },
	{ theme = "ayu-light", filename = "syntax-theme-light.css" },
]

[extra]
social_links = [
	{ name = "itch.io", url = "https://tesselode.itch.io/", icon = "fab fa-itch-io" },
	{ name = "Bandcamp", url = "https://tesselode.bandcamp.com/", icon = "fab fa-bandcamp" },
	{ name = "GitHub", url = "https://github.com/tesselode/", icon = "fab fa-github" },
	{ name = "Bluesky", url = "https://bsky.app/profile/tesselode.bsky.social", icon = "fa-brands fa-bluesky" },
	{ name = "YouTube", url = "https://www.youtube.com/@tesselode", icon = "fa-brands fa-youtube" },
]
